# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title                    : "iFEM: an Integrated Finite Element Methods Package in MATLAB"
# title_separator          : "-"
# subtitle                 : "an Integrated Finite Element Methods Package in MATLAB"
email: chenlong@math.uci.edu
description: >- # this means to ignore newlines until "baseurl:"
  iFEM is a MATLAB software package containing robust, efficient, and easy-following codes for the main building blocks of adaptive finite element methods on unstructured simplicial grids in both two and three dimensions. Besides the simplicity and readability, sparse matrixlization, an innovative programming style for MATLAB, is introduced to improve the efficiency. In this novel coding style, the sparse matrix and its operations are used extensively in the data structure and algorithms.
baseurl: "/ifem" # the subpath of your site, e.g. /blog
url: "https://lyc102.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
atom_feed:
  hide: true

repository: lyc102/ifem
repository_tree: master

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
search: true
search_full_content: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
  # syntax_highlighter: rouge // new version, github pages need the old one
permalink   : date

comments:
 provider: "disqus"
 disqus:
  shortname: "https-lyc102-github-io"

include:
  - _pages
  - _fem
  - _afem
  - _dof
  - _mesh
  - _solver
  - _research
  - _projects

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

## => Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "docs"
      mathjax: true
  # _pages: general pages in iFEM
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
      mathjax: true
      toc: true
      toc_sticky: true
  # _fem: for finite element documents
  - scope:
      path: "_fem"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "fem"
      mathjax: true
      toc: true
      toc_sticky: true
  # _afem: for adaptive finite element documents
  - scope:
      path: "_afem"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "afem"
      mathjax: true
      toc: true
      toc_sticky: true
  # _mesh: for mesh documents
  - scope:
      path: "_mesh"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "mesh"
      mathjax: true
      toc: true
      toc_sticky: true
  # _dof: for dofs documents
  - scope:
      path: "_dof"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "mesh"
      mathjax: true
      toc: true
      toc_sticky: true
  # _solver: for solver docs
  - scope:
      path: "_solver"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "docs"
      mathjax: true
      toc: true
      toc_sticky: true
  # _projects: project pages
  - scope:
      path: "_projects"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "project"
      mathjax: true
      toc: true
      toc_sticky: true
  # _research
  - scope:
      path: "_research"
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      sidebar:
        nav: "research"
      mathjax: true
      toc: true
      toc_sticky: true

# Outputting
permalink: /:categories/:title/

category_archive:
  type: liquid
  path: /categories/
